<?php
$coverage = new PHP_CodeCoverage;
$coverage->setData(array (
  '/home/julian/PhpstormProjects/PermutatorTest/src/SomeClass.php' => 
  array (
    12 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    13 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    14 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    15 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    17 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    18 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    19 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    20 => NULL,
    24 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    25 => 
    array (
      0 => 'SomeClassTest::testSomeClass',
    ),
    29 => 
    array (
    ),
    30 => 
    array (
    ),
  ),
));
$coverage->setTests(array (
  'SomeClassTest::testSomeClass' => 0,
));

$filter = $coverage->filter();
$filter->setBlacklistedFiles(array (
  '/home/julian/PhpstormProjects/PermutatorTest/test/SomeClassTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/TestCase.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Assert.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-file-iterator/File/Iterator.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-file-iterator/File/Iterator/Autoload.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-file-iterator/File/Iterator/Facade.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-file-iterator/File/Iterator/Factory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/HHVM.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/Xdebug.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Exception/UnintentionallyCoveredCode.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Filter.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Clover.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Crap4j.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Factory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Dashboard.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Directory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/File.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Node.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Node/Directory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Node/File.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Node/Iterator.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/PHP.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Text.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/Directory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/File.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/File/Coverage.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/File/Method.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/File/Report.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/File/Unit.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/Node.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/Project.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/Tests.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/XML/Totals.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Util.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-code-coverage/src/CodeCoverage/Util/InvalidArgumentHelper.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-timer/PHP/Timer.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-timer/PHP/Timer/Autoload.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-token-stream/PHP/Token.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-token-stream/PHP/Token/Stream.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-token-stream/PHP/Token/Stream/Autoload.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-token-stream/PHP/Token/Stream/CachingFactory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Extensions/GroupTestSuite.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Extensions/PhptTestCase.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Extensions/PhptTestSuite.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Extensions/RepeatedTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Extensions/TestDecorator.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Extensions/TicketListener.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/AssertionFailedError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/BaseTestListener.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/CodeCoverageException.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Array.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/DOMNode.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/DateTime.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Double.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/MockObject.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Numeric.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Object.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Resource.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Scalar.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/SplObjectStorage.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Comparator/Type.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/ComparatorFactory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/ComparisonFailure.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/And.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/ArrayHasKey.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Attribute.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Callback.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/ClassHasAttribute.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/ClassHasStaticAttribute.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Composite.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Count.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/ExceptionCode.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/ExceptionMessage.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/FileExists.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/GreaterThan.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsAnything.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsEmpty.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsEqual.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsFalse.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsIdentical.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsInstanceOf.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsJson.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsNull.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsTrue.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/IsType.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/JsonMatches.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/JsonMatches/ErrorMessageProvider.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/LessThan.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Not.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/ObjectHasAttribute.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Or.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/PCREMatch.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/SameSize.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/StringContains.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/StringEndsWith.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/StringMatches.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/StringStartsWith.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/TraversableContains.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/TraversableContainsOnly.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Constraint/Xor.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Error.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Error/Deprecated.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Error/Notice.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Error/Warning.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/ExpectationFailedException.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/IncompleteTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/IncompleteTestError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/InvalidCoversTargetError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/InvalidCoversTargetException.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/OutputError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/RiskyTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/RiskyTestError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/SelfDescribing.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/SkippedTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/SkippedTestError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/SkippedTestSuiteError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/SyntheticError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Test.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/TestFailure.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/TestListener.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/TestResult.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/TestSuite.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/TestSuite/DataProvider.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/UnintentionallyCoveredCodeError.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Framework/Warning.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Filter/Factory.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Filter/Group.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Filter/Group/Exclude.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Filter/Group/Include.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Filter/Test.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/TestSuiteLoader.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Runner/Version.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/TextUI/Command.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/TextUI/TestRunner.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Blacklist.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Configuration.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/DeprecatedFeature.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/DeprecatedFeature/Logger.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/ErrorHandler.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Fileloader.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Filesystem.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Filter.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Getopt.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/GlobalState.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/InvalidArgumentHelper.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Log/JSON.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Log/JUnit.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Log/TAP.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/PHP.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/PHP/Default.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/PHP/Windows.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Printer.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/String.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Test.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/TestDox/NamePrettifier.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/TestDox/ResultPrinter.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/TestDox/ResultPrinter/HTML.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/TestDox/ResultPrinter/Text.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/TestSuiteIterator.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/Type.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit/src/Util/XML.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/Identity.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/InvocationMocker.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/Match.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/MethodNameMatch.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/Namespace.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/ParametersMatch.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Builder/Stub.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Invocation.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Invocation/Object.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Invocation/Static.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/InvocationMocker.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Invokable.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/AnyInvokedCount.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/AnyParameters.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/Invocation.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/InvokedAtIndex.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/InvokedAtLeastOnce.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/InvokedCount.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/InvokedRecorder.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/MethodName.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/Parameters.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Matcher/StatelessInvocation.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockBuilder.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockObject.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/ConsecutiveCalls.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/MatcherCollection.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/Return.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/ReturnArgument.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/ReturnCallback.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/ReturnSelf.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub/ReturnValueMap.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Verifiable.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-text-template/Text/Template.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/phpunit/php-text-template/Text/Template/Autoload.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Dumper.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Escaper.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Exception/DumpException.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Exception/ExceptionInterface.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Exception/ParseException.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Exception/RuntimeException.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Inline.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Parser.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Tests/DumperTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Tests/InlineTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Tests/ParseExceptionTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Tests/ParserTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Tests/YamlTest.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Unescaper.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/symfony/yaml/Symfony/Component/Yaml/Yaml.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/sebastian/environment/src/Runtime.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/sebastian/exporter/src/Context.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/sebastian/exporter/src/Exception.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/sebastian/exporter/src/Exporter.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/sebastian/version/src/Version.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/sebastian/version/src/autoload.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/composer/ClassLoader.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/composer/autoload_classmap.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/composer/autoload_namespaces.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/composer/autoload_psr4.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/composer/autoload_real.php' => true,
  '/home/julian/PhpstormProjects/PermutatorTest/vendor/composer/include_paths.php' => true,
));
$filter->setWhitelistedFiles(array (
));

return $coverage;